export type PersonaStartstatus = "startwelle" | "backlog";
export type PersonaOperatorKey = "gruender" | "partner";

export type PersonaScores = {
  instagramReach: number;
  affiliateFit: number;
  assetEase: number;
  setcardQuality: number;
  repeatability: number;
  differentiation: number;
  complianceEase: number;
  operatorFit: number;
};

export type PersonaPortfolioItem = {
  order: number;
  name: string;
  publicName: string;
  archetype: string;
  lane: string;
  niche: string;
  startstatus: PersonaStartstatus;
  operatorKey: PersonaOperatorKey | null;
  launchWaveOrder: number | null;
  instagramHandle: string;
  setcardStatus: "bereit" | "pruefen" | "fehlt";
  mediaReadinessStatus: "bereit" | "aufbauen" | "offen";
  scores: PersonaScores;
  nextActivationCondition: string;
  backlogActivationNote: string | null;
  contentWedge: string;
  monetizationNotes: string;
};

export const PERSONA_PORTFOLIO: PersonaPortfolioItem[] = [
  {
    order: 1,
    name: "Luna Stone",
    publicName: "Luna Stone",
    archetype: "Clean Girl Aesthetic Creator + Slow Living Advocate",
    lane: "Minimalismus / Slow Living",
    niche: "ruhige Routinen, nachhaltige Produkte und visuelle Ordnung",
    startstatus: "startwelle",
    operatorKey: "gruender",
    launchWaveOrder: 3,
    instagramHandle: "luna.stone",
    setcardStatus: "pruefen",
    mediaReadinessStatus: "aufbauen",
    scores: score(4, 4, 4, 3, 4, 4, 5, 4),
    nextActivationCondition: "Startwelle: ruhige Bildsprache und 30-Tage-Routinen vorbereiten.",
    backlogActivationNote: null,
    contentWedge: "Minimalistische Alltagsroutinen mit klarer Produkt- und Ordnungslogik.",
    monetizationNotes: "Nachhaltige Haushaltsprodukte, Journaling, Organisationshelfer und Beauty-Basics."
  },
  {
    order: 2,
    name: "Jake Steele",
    publicName: "Jake Steele",
    archetype: "Sigma Commentator + Pragmatic Hustler",
    lane: "Mindset / Hustle",
    niche: "pragmatische Karriere- und Disziplin-Kommentare",
    startstatus: "backlog",
    operatorKey: null,
    launchWaveOrder: null,
    instagramHandle: "jake.steele",
    setcardStatus: "fehlt",
    mediaReadinessStatus: "offen",
    scores: score(3, 3, 4, 2, 4, 3, 3, 3),
    nextActivationCondition: "Aktivieren, wenn klare Abgrenzung zu toxischer Hustle-Sprache steht.",
    backlogActivationNote: "Ton und Claim-Grenzen zuerst schärfen.",
    contentWedge: "Direkte, kurze Realitätschecks für Fokus und Arbeitsethik.",
    monetizationNotes: "Produktivitätstools, Bücher, Kurse nur mit nüchterner Erwartung."
  },
  {
    order: 3,
    name: "Mira Chen",
    publicName: "Mira Chen",
    archetype: "Dark Academia Thinker + Cozy Aesthetic Creator",
    lane: "Lifestyle / Bildung",
    niche: "Lernen, Lesen, Notizen und dunkle Cozy-Ästhetik",
    startstatus: "backlog",
    operatorKey: null,
    launchWaveOrder: null,
    instagramHandle: "mira.chen",
    setcardStatus: "fehlt",
    mediaReadinessStatus: "offen",
    scores: score(3, 3, 4, 2, 4, 4, 5, 3),
    nextActivationCondition: "Aktivieren, wenn 20 wiederholbare Lern- und Leseformate stehen.",
    backlogActivationNote: "Setcard und visuelle Welt fehlen noch.",
    contentWedge: "Studier- und Denkroutinen mit ästhetischem Mehrwert.",
    monetizationNotes: "Notizbücher, Schreibwaren, Leselampen, Lern-Apps."
  },
  {
    order: 4,
    name: "Alex Moreno",
    publicName: "Alex Moreno",
    archetype: "High-Energy Fitness Creator + Motivation-Coach",
    lane: "Fitness / Motivation",
    niche: "Disziplin, Anfänger-Routinen und Gym-Angst abbauen",
    startstatus: "startwelle",
    operatorKey: "partner",
    launchWaveOrder: 4,
    instagramHandle: "alex.moreno",
    setcardStatus: "pruefen",
    mediaReadinessStatus: "aufbauen",
    scores: score(5, 4, 3, 3, 5, 4, 3, 4),
    nextActivationCondition: "Startwelle: Fitness-Claims strikt ohne Fake-Transformationen halten.",
    backlogActivationNote: null,
    contentWedge: "Fitnesspsychologie und einfache Routinen statt falscher Ergebnisversprechen.",
    monetizationNotes: "Fitness-Apps, Trainingspläne, Home-Gym-Zubehör, Supplements mit Claim-Kontrolle."
  },
  {
    order: 5,
    name: "Sophie Larue",
    publicName: "Sophie Larue",
    archetype: "Y2K Fashion It-Girl + Trendsetter",
    lane: "Fashion / Trends",
    niche: "Y2K-Outfits, Styling-Regeln und Shopping-nahe Inspiration",
    startstatus: "startwelle",
    operatorKey: "partner",
    launchWaveOrder: 5,
    instagramHandle: "sophie.larue",
    setcardStatus: "pruefen",
    mediaReadinessStatus: "aufbauen",
    scores: score(5, 5, 4, 3, 4, 4, 4, 4),
    nextActivationCondition: "Startwelle: Trendtempo und visuelle Konsistenz absichern.",
    backlogActivationNote: null,
    contentWedge: "Outfit-Formeln und Y2K-Trends, die direkt speicherbar sind.",
    monetizationNotes: "Fashion-Affiliates, Accessoires, Secondhand-Plattformen."
  },
  {
    order: 6,
    name: "Marcus Reed",
    publicName: "Marcus Reed",
    archetype: "Corporate Anti-Hero + System-Breaker",
    lane: "Karriere / Büro-Realität",
    niche: "Corporate-Kommentare, Büro-Politik und Systemkritik",
    startstatus: "backlog",
    operatorKey: null,
    launchWaveOrder: null,
    instagramHandle: "marcus.reed",
    setcardStatus: "fehlt",
    mediaReadinessStatus: "offen",
    scores: score(3, 3, 4, 2, 4, 4, 4, 3),
    nextActivationCondition: "Aktivieren, wenn der Ton scharf, aber nicht zynisch ist.",
    backlogActivationNote: "Braucht klare Content-Grenzen gegen generische LinkedIn-Satire.",
    contentWedge: "Karriere-Realismus ohne leere Motivationssätze.",
    monetizationNotes: "Produktivität, Bewerbungs-Tools, Kurse nur soft."
  },
  {
    order: 7,
    name: "Zara Patel",
    publicName: "Zara Patel",
    archetype: "Inclusive Beauty Creator + Educator",
    lane: "Beauty / Skincare",
    niche: "inklusive Beauty, Hautbarriere und ruhige Produktbildung",
    startstatus: "startwelle",
    operatorKey: "gruender",
    launchWaveOrder: 2,
    instagramHandle: "zara.patel",
    setcardStatus: "pruefen",
    mediaReadinessStatus: "aufbauen",
    scores: score(5, 5, 3, 3, 4, 5, 3, 4),
    nextActivationCondition: "Startwelle: Beauty-Claims und Fake-Usage strikt vermeiden.",
    backlogActivationNote: null,
    contentWedge: "Routinen, Inhaltsstoffe und undertone-sichere Beauty-Erklärungen.",
    monetizationNotes: "Skincare, Haircare, Beauty-Tools, shade-inclusive Produkte."
  },
  {
    order: 8,
    name: "Nate Jackson",
    publicName: "Nate Jackson",
    archetype: "Streetwise Hustler + Entrepreneur Mindset",
    lane: "Business / Mindset",
    niche: "kleine Geschäftsmodelle, Nebenverdienst und harte Lernkurven",
    startstatus: "backlog",
    operatorKey: null,
    launchWaveOrder: null,
    instagramHandle: "nate.jackson",
    setcardStatus: "fehlt",
    mediaReadinessStatus: "offen",
    scores: score(3, 4, 4, 2, 4, 3, 3, 3),
    nextActivationCondition: "Aktivieren, wenn Finanz- und Einkommensclaims wasserdicht sind.",
    backlogActivationNote: "Hohes Claim-Risiko bei Money-Content.",
    contentWedge: "Realistische kleine Business-Lektionen ohne Erfolgsversprechen.",
    monetizationNotes: "Business-Tools, Bücher, Templates, keine Income-Guarantees."
  },
  {
    order: 9,
    name: "Emma Winters",
    publicName: "Emma Winters",
    archetype: "Realistic Mom + Home Organizer",
    lane: "Home / Organisation",
    niche: "realistische Ordnung, Familienhaushalt und kleine Systeme",
    startstatus: "startwelle",
    operatorKey: "partner",
    launchWaveOrder: 6,
    instagramHandle: "emma.winters",
    setcardStatus: "pruefen",
    mediaReadinessStatus: "aufbauen",
    scores: score(4, 5, 4, 3, 5, 4, 5, 4),
    nextActivationCondition: "Startwelle: alltagsnahe Ordnungsformate und Affiliate-Fit vorbereiten.",
    backlogActivationNote: null,
    contentWedge: "Ordnungssysteme, die im echten Alltag nicht perfekt aussehen müssen.",
    monetizationNotes: "Haushaltshelfer, Aufbewahrung, Familienorganisation, Cleaning-Produkte."
  },
  {
    order: 10,
    name: "David Chen",
    publicName: "David Chen",
    archetype: "Tech Explainer + AI Educator",
    lane: "AI / Produktivität",
    niche: "Workflow-first AI, Automationen und Solo-Operator-Leverage",
    startstatus: "startwelle",
    operatorKey: "gruender",
    launchWaveOrder: 1,
    instagramHandle: "david.chen",
    setcardStatus: "bereit",
    mediaReadinessStatus: "bereit",
    scores: score(5, 5, 5, 4, 5, 5, 4, 5),
    nextActivationCondition: "Startwelle: keine generischen Tool-Listen, nur Workflow-Beweise.",
    backlogActivationNote: null,
    contentWedge: "Karussells über konkrete AI-Workflows und Automationssysteme.",
    monetizationNotes: "AI-SaaS-Affiliates, Produktivitätstools, Templates, Mini-Produkte."
  },
  {
    order: 11,
    name: "Isabella Rosa",
    publicName: "Isabella Rosa",
    archetype: "Luxury Lifestyle Curator + Aspiration Creator",
    lane: "Luxury / Lifestyle",
    niche: "kuratierter Luxus, Reisen und gehobene Alltagsästhetik",
    startstatus: "backlog",
    operatorKey: null,
    launchWaveOrder: null,
    instagramHandle: "isabella.rosa",
    setcardStatus: "fehlt",
    mediaReadinessStatus: "offen",
    scores: score(4, 4, 3, 2, 3, 3, 4, 2),
    nextActivationCondition: "Aktivieren, wenn Bildrealismus und Orts-/Produktclaims geklärt sind.",
    backlogActivationNote: "Luxus wirkt schnell fake, visuelle Qualität muss hoch sein.",
    contentWedge: "Aspirative Moodboards und kuratierte Einkaufsideen ohne Fake-Lifestyle-Behauptungen.",
    monetizationNotes: "Fashion, Travel-Accessoires, Beauty, Home Decor."
  },
  {
    order: 12,
    name: "Tyler Brooks",
    publicName: "Tyler Brooks",
    archetype: "Niche Gaming Creator + Tech Enthusiast",
    lane: "Gaming / Tech",
    niche: "Gaming-Setup, Indie-Games und Hardware-Tipps",
    startstatus: "backlog",
    operatorKey: null,
    launchWaveOrder: null,
    instagramHandle: "tyler.brooks",
    setcardStatus: "fehlt",
    mediaReadinessStatus: "offen",
    scores: score(3, 4, 4, 2, 4, 3, 4, 3),
    nextActivationCondition: "Aktivieren, wenn genug wiederholbare Setup- und Game-Formate stehen.",
    backlogActivationNote: "Gaming braucht klare visuelle Nische, sonst zu breit.",
    contentWedge: "Setup-Verbesserungen und kurze Game-Entdeckungen für speicherbare Posts.",
    monetizationNotes: "Gaming-Zubehör, Peripherie, Software, digitale Angebote."
  },
  {
    order: 13,
    name: "Victoria Sokolov",
    publicName: "Victoria Sokolov",
    archetype: "Wellness Coach + Meditation Guide",
    lane: "Wellness / Meditation",
    niche: "Achtsamkeit, Stressregulation und sanfte Routinen",
    startstatus: "backlog",
    operatorKey: null,
    launchWaveOrder: null,
    instagramHandle: "victoria.sokolov",
    setcardStatus: "fehlt",
    mediaReadinessStatus: "offen",
    scores: score(3, 4, 4, 2, 4, 3, 3, 3),
    nextActivationCondition: "Aktivieren, wenn Wellness-Claims ohne medizinische Wirkung formuliert sind.",
    backlogActivationNote: "Gesundheitsclaims zuerst absichern.",
    contentWedge: "Kleine Ruhe-Rituale ohne Therapie- oder Heilversprechen.",
    monetizationNotes: "Meditations-Apps, Journals, Aromaprodukte, Schlafhelfer."
  },
  {
    order: 14,
    name: "Jason Parker",
    publicName: "Jason Parker",
    archetype: "Career Coach + Professional Resume Expert",
    lane: "Karriere / Bewerbung",
    niche: "Lebenslauf, Bewerbung, Interview und Jobwechsel",
    startstatus: "backlog",
    operatorKey: null,
    launchWaveOrder: null,
    instagramHandle: "jason.parker",
    setcardStatus: "fehlt",
    mediaReadinessStatus: "offen",
    scores: score(3, 4, 5, 2, 5, 3, 4, 3),
    nextActivationCondition: "Aktivieren, wenn 30 Carousel-Templates für Bewerbungsprobleme stehen.",
    backlogActivationNote: "Stark für Karussells, aber weniger visuell als Startwelle.",
    contentWedge: "Konkrete Bewerbungs- und Interview-Verbesserungen in Vorher/Nachher-Formaten.",
    monetizationNotes: "Resume-Tools, Templates, Karriere-Kurse, Interview-Software."
  },
  {
    order: 15,
    name: "Lily Wang",
    publicName: "Lily Wang",
    archetype: "Sustainable Fashion Advocate + Thrift-Expert",
    lane: "Sustainable Fashion",
    niche: "Secondhand, Capsule Wardrobe und bewusster Konsum",
    startstatus: "backlog",
    operatorKey: null,
    launchWaveOrder: null,
    instagramHandle: "lily.wang",
    setcardStatus: "fehlt",
    mediaReadinessStatus: "offen",
    scores: score(4, 4, 4, 2, 4, 4, 5, 3),
    nextActivationCondition: "Aktivieren, wenn Sophie-Daten zeigen, welche Fashion-Formate tragen.",
    backlogActivationNote: "Kann später als nachhaltiger Gegenpol zu Sophie starten.",
    contentWedge: "Thrift-Regeln und Capsule-Outfits mit konkreten Einkaufsentscheidungen.",
    monetizationNotes: "Secondhand-Plattformen, nachhaltige Marken, Pflegeprodukte."
  },
  {
    order: 16,
    name: "Carlos Santos",
    publicName: "Carlos Santos",
    archetype: "Home Improvement Master + DIY Educator",
    lane: "DIY / Home Improvement",
    niche: "kleine Reparaturen, Werkzeug und Mietwohnungs-Upgrades",
    startstatus: "backlog",
    operatorKey: null,
    launchWaveOrder: null,
    instagramHandle: "carlos.santos",
    setcardStatus: "fehlt",
    mediaReadinessStatus: "offen",
    scores: score(4, 5, 3, 2, 4, 4, 4, 3),
    nextActivationCondition: "Aktivieren, wenn sichere DIY-Claims und Bildmaterial möglich sind.",
    backlogActivationNote: "Braucht sauberes Material und Haftungsgrenzen.",
    contentWedge: "Kleine, sichere Home-Upgrades mit Werkzeug- und Materiallisten.",
    monetizationNotes: "Werkzeug, Home-Repair-Kits, Baumarkt-Affiliates."
  },
  {
    order: 17,
    name: "Amelie Fontaine",
    publicName: "Amelie Fontaine",
    archetype: "French Beauty Minimalist + Skincare Guru",
    lane: "Beauty / Minimalismus",
    niche: "französische Beauty, minimalistische Routinen und Hautpflege",
    startstatus: "backlog",
    operatorKey: null,
    launchWaveOrder: null,
    instagramHandle: "amelie.fontaine",
    setcardStatus: "fehlt",
    mediaReadinessStatus: "offen",
    scores: score(4, 5, 3, 2, 4, 4, 3, 3),
    nextActivationCondition: "Aktivieren, wenn Zara-Formate validiert sind und Abgrenzung klar ist.",
    backlogActivationNote: "Nicht gleichzeitig mit Zara starten, sonst Beauty-Fokus verwässert.",
    contentWedge: "Weniger Produkte, bessere Routine-Entscheidungen, französisch-minimaler Stil.",
    monetizationNotes: "Skincare, Parfum, Beauty-Tools, minimalistische Marken."
  },
  {
    order: 18,
    name: "Blake Morgan",
    publicName: "Blake Morgan",
    archetype: "Crypto Educator + Finance Explainer",
    lane: "Finance / Crypto",
    niche: "Krypto-Grundlagen, Risikodenken und Marktverständnis",
    startstatus: "backlog",
    operatorKey: null,
    launchWaveOrder: null,
    instagramHandle: "blake.morgan",
    setcardStatus: "fehlt",
    mediaReadinessStatus: "offen",
    scores: score(4, 5, 5, 2, 4, 3, 1, 2),
    nextActivationCondition: "Aktivieren nur mit strenger Finanz-Disclosure und ohne Anlageberatung.",
    backlogActivationNote: "Sehr monetarisierbar, aber höchstes Compliance-Risiko.",
    contentWedge: "Risikobewusste Krypto-Erklärungen ohne Kaufempfehlungen.",
    monetizationNotes: "Finanztools nur nach Regelcheck, keine Renditeversprechen."
  },
  {
    order: 19,
    name: "Sophia Novak",
    publicName: "Sophia Novak",
    archetype: "Personal Development Coach + Confidence Builder",
    lane: "Persönlichkeitsentwicklung",
    niche: "Selbstvertrauen, Grenzen und soziale Sicherheit",
    startstatus: "backlog",
    operatorKey: null,
    launchWaveOrder: null,
    instagramHandle: "sophia.novak",
    setcardStatus: "fehlt",
    mediaReadinessStatus: "offen",
    scores: score(3, 3, 4, 2, 4, 3, 4, 3),
    nextActivationCondition: "Aktivieren, wenn klare Differenzierung gegen generische Coaching-Posts steht.",
    backlogActivationNote: "Braucht harte Formate, sonst zu allgemein.",
    contentWedge: "Praktische Confidence-Skripte und Grenzen im Alltag.",
    monetizationNotes: "Journals, Kurse, Bücher, Apps mit vorsichtiger Sprache."
  },
  {
    order: 20,
    name: "Jackson Wright",
    publicName: "Jackson Wright",
    archetype: "Authentic Outdoor Adventure Creator + Gear Reviewer",
    lane: "Outdoor / Gear",
    niche: "Outdoor-Abenteuer, Ausrüstung und einfache Tourenplanung",
    startstatus: "backlog",
    operatorKey: null,
    launchWaveOrder: null,
    instagramHandle: "jackson.wright",
    setcardStatus: "fehlt",
    mediaReadinessStatus: "offen",
    scores: score(4, 5, 3, 2, 4, 4, 4, 3),
    nextActivationCondition: "Aktivieren, wenn Bildmaterial glaubwürdig und gear-lastig genug ist.",
    backlogActivationNote: "Outdoor braucht starke Medien, sonst wirkt es konstruiert.",
    contentWedge: "Gear-Entscheidungen und kleine Abenteuer ohne Fake-Ortsbehauptungen.",
    monetizationNotes: "Outdoor-Gear, Kleidung, Rucksäcke, Planungs-Apps."
  },
  {
    order: 21,
    name: "Elias Vogel",
    publicName: "Elias Vogel",
    archetype: "Heritage Craftsman + Stoic Outdoorsman",
    lane: "Outdoor / Handwerk",
    niche: "Holzarbeiten, Bergleben, stoische Alltagsphilosophie",
    startstatus: "backlog",
    operatorKey: null,
    launchWaveOrder: null,
    instagramHandle: "elias.vogel",
    setcardStatus: "fehlt",
    mediaReadinessStatus: "offen",
    scores: score(4, 4, 3, 2, 4, 5, 5, 3),
    nextActivationCondition: "Aktivieren, wenn Craft-Bildmaterial und stoische Claim-Grenzen stehen.",
    backlogActivationNote: "Starkes Differenzierungspotenzial, braucht aber handwerkliches Bildmaterial.",
    contentWedge: "Handwerk-Tutorials und Alpine-Alltagsweisheiten ohne konstruierte Romantik.",
    monetizationNotes: "Werkzeug, Outdoor-Marken, Craft-Kits, Heritage-Kleidung."
  },
  {
    order: 22,
    name: "Zara Sky",
    publicName: "Zara Sky",
    archetype: "Spiritual Tech Nomad + Wellness Architect",
    lane: "Wellness / Digital Nomad",
    niche: "Achtsamkeit, Nomaden-Lifestyle, spirituelle Selbstoptimierung",
    startstatus: "backlog",
    operatorKey: null,
    launchWaveOrder: null,
    instagramHandle: "zara.sky",
    setcardStatus: "fehlt",
    mediaReadinessStatus: "offen",
    scores: score(4, 4, 4, 2, 4, 4, 4, 3),
    nextActivationCondition: "Aktivieren, wenn Wellness-Claims ohne medizinische Wirkung und Bali-Bildmaterial gesichert sind.",
    backlogActivationNote: "Ähnlich zu Victoria Sokolov – Abgrenzung über Nomaden-Lifestyle.",
    contentWedge: "Spirituelle Reise-Routinen ohne Heilversprechen und Fake-Ortsbehauptungen.",
    monetizationNotes: "Reise-Tools, Wellness-Apps, nachhaltige Produkte, Yoga-Zubehör."
  },
  {
    order: 23,
    name: "Amina Koroma",
    publicName: "Amina Koroma",
    archetype: "Afro-Futurist Designer + Tech-Weaver",
    lane: "Fashion / Design / Tech",
    niche: "Afro-futuristische Mode, Tech-Stoffe, kulturelles Design-Storytelling",
    startstatus: "backlog",
    operatorKey: null,
    launchWaveOrder: null,
    instagramHandle: "amina.koroma",
    setcardStatus: "fehlt",
    mediaReadinessStatus: "offen",
    scores: score(4, 4, 4, 2, 4, 5, 4, 3),
    nextActivationCondition: "Aktivieren, wenn starke redaktionelle Bildwelt und klare Differenzierung zu Sophie stehen.",
    backlogActivationNote: "Hohe kulturelle Tiefe – braucht editorial-starke Bilder und klare Story.",
    contentWedge: "Mode als kulturelles Statement mit konkreten Design- und Produktideen.",
    monetizationNotes: "Designer-Brands, Tech-Fashion, kulturelle Kollektionen, Accessoires."
  },
  {
    order: 24,
    name: "Marcus Thorne",
    publicName: "Marcus Thorne",
    archetype: "Quiet Luxury + Investment Strategist",
    lane: "Finance / Quiet Luxury",
    niche: "Old Money Stil, Investment-Denken, diskreter Wohlstand",
    startstatus: "backlog",
    operatorKey: null,
    launchWaveOrder: null,
    instagramHandle: "marcus.thorne",
    setcardStatus: "fehlt",
    mediaReadinessStatus: "offen",
    scores: score(4, 5, 3, 2, 4, 4, 2, 3),
    nextActivationCondition: "Aktivieren nur mit strenger Finanz-Disclosure und ohne Anlageberatung.",
    backlogActivationNote: "Sehr monetarisierbar, aber höchstes Compliance-Risiko im Finance-Bereich.",
    contentWedge: "Diskrete Wohlstandsästhetik und Investment-Mindset ohne Renditeversprechen.",
    monetizationNotes: "Finanztools nur nach Regelcheck, Luxury-Affiliates, Heritage-Marken."
  }
];

function score(
  instagramReach: number,
  affiliateFit: number,
  assetEase: number,
  setcardQuality: number,
  repeatability: number,
  differentiation: number,
  complianceEase: number,
  operatorFit: number
): PersonaScores {
  return {
    instagramReach,
    affiliateFit,
    assetEase,
    setcardQuality,
    repeatability,
    differentiation,
    complianceEase,
    operatorFit
  };
}
